### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by coderschoolreview** [dodongphure/blog#1]
Hi @dodongphure, thanks for your hard work on pre-work submission. You’ve done good job so far, only 3 hours to finish required story. However, we haven't seen your heroku link yet. Please deploy your blog to heroku following the instruction from our walkthrough and update README file with the heroku URL.

If you have any trouble with deployment, feel free to comment here or use [gitter chat](https://gitter.im/coderschool/ruby). We are happy to help.

Best regards,

**Comment by dodongphure** [comment]
Yeah, I updated README (3 days ago). My heroku: http://phublogs.herokuapp.com/.
P/s: sorry for reply late :)

Cheers,
